name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
          JENKINS_JOB_NAME: "jenkins"
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build" \
          --user "$JENKINS_USER:$JENKINS_PASSWORD"
