version: '3'
services:
  quant:
    image: library/mysql:8.3
    container_name: quant-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quant
      MYSQL_USER: quant
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
      DB_HOST: host.docker.internal
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
